---
- name: Run setup tasks for pod
  hosts: localhost
  gather_facts: no

  tasks:

#  - name: Wait for CSRs to boot
#    pause:
#      minutes: 5


- name: Run setup tasks for pod
  hosts: csrs
  gather_facts: no

  tasks:

  - name: VERIFYING CONNECTIVITY
    wait_for:
      port: 22
      delay: 300
      timeout: 300

  - name: GATHERING FACTS
    ios_facts:
      gather_subset: hardware

  - name: Show current version
    debug: msg="Current version for {{ansible_host}} is {{ansible_net_version}}"

  - name: Enable CDP
    ios_config:
      lines:
        - cdp run

  - name: Disable CDP on Gi0/0
    ios_config:
      lines:
        - no cdp enable
      parents:
        - interface Gig0/0

